In [22]:
from sklearn import preprocessing
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

### 1.Получите данные и загрузите их в рабочую среду. (Jupyter Notebook или другую)

In [2]:
data=pd.read_csv('heart.csv')
data

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

### Подготовьте датасет к обучению моделей:
### a) Категориальные переменные переведите в цифровые значения. Можно использовать pd.get_dummies, preprocessing.LabelEncoder. Старайтесь не использовать для этой задачи циклы.

In [4]:
le = preprocessing.LabelEncoder()
le.fit(data['HeartDisease'])

LabelEncoder()

In [5]:
list(le.classes_)

[0, 1]

In [6]:
y = le.transform(data['HeartDisease'])

In [7]:
data.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [8]:
X = data[['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope']]

In [9]:
X = pd.get_dummies(data=data, columns=['Sex', 'ChestPainType','RestingECG', 'ExerciseAngina', 'ST_Slope'])
# удаляем два столбца
# если 'Sex_M' = 0, это женщина
# если 'ExerciseAngina_N' = 0 , то 'ExerciseAngina_M'
X.drop(columns=['Sex_F', 'ExerciseAngina_N'],inplace=True)

In [10]:
X

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,0,1,0,0,0,1,0,0,0,0,1
1,49,160,180,0,156,1.0,1,0,0,0,1,0,0,1,0,0,0,1,0
2,37,130,283,0,98,0.0,0,1,0,1,0,0,0,0,1,0,0,0,1
3,48,138,214,0,108,1.5,1,0,1,0,0,0,0,1,0,1,0,1,0
4,54,150,195,0,122,0.0,0,1,0,0,1,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,1,0,0,0,1,0,1,0,0,0,1,0
914,68,144,193,1,141,3.4,1,1,1,0,0,0,0,1,0,0,0,1,0
915,57,130,131,0,115,1.2,1,1,1,0,0,0,0,1,0,1,0,1,0
916,57,130,236,0,174,0.0,1,0,0,1,0,0,1,0,0,0,0,1,0
917,38,138,175,0,173,0.0,0,1,0,0,1,0,0,1,0,0,0,0,1

In [11]:
[len(data[col].value_counts()) for col in data.columns]

[50, 2, 4, 67, 222, 2, 3, 119, 2, 53, 3, 2]

### 3.Разделите выборку на обучающее и тестовое подмножество. 80% данных оставить на обучающее множество, 20% на тестовое.

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

### 4. Обучите модель логистической регрессии с параметрами по умолчанию.

In [23]:
clf = LogisticRegression(random_state=0).fit(X_train, y_train)

### 5. Оптимизируйте 3-4 параметра модели:

In [35]:
from sklearn.model_selection import cross_validate

knn = KNeighborsClassifier(n_neighbors=5)
scores = cross_validate(knn, X_train, y_train, cv=10, scoring=['accuracy','recall','precision','f1'])
for i in scores.keys():
    print(i, ' ',scores[i].round(3),'\n')
# print(scores.mean())

fit_time   [0.006 0.002 0.002 0.002 0.002 0.002 0.002 0.002 0.001 0.002]

score_time   [0.009 0.007 0.007 0.006 0.006 0.007 0.007 0.007 0.006 0.007]

test_accuracy   [0.77  0.676 0.757 0.73  0.74  0.699 0.685 0.685 0.658 0.74 ]

test_recall   [0.85  0.75  0.775 0.854 0.8   0.725 0.675 0.675 0.75  0.775]

test_precision   [0.756 0.682 0.775 0.714 0.744 0.725 0.73  0.73  0.667 0.756]

test_f1   [0.8   0.714 0.775 0.778 0.771 0.725 0.701 0.701 0.706 0.765]

### 6. Оптимизируйте 3-4 параметра модели:

In [37]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV

In [ ]:
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters)
clf.fit(X_train, y_train)

In [ ]:
sorted(clf.cv_results_.keys())